//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTS_2019.BLL.UC_CarOrder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.UC_CarOrder.UC_CarOrder")]
    public interface UC_CarOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainType", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainTypeResponse")]
        System.Data.DataSet UserControl_Loaded_SelectTrainType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainType", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectOrder", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectOrderResponse")]
        System.Data.DataSet UserControl_Loaded_SelectOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectOrder", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectOrderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectOrderDetail", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectOrderDetailResponse")]
        System.Data.DataSet UserControl_Loaded_SelectOrderDetail(int intorder_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectOrderDetail", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectOrderDetailResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectOrderDetailAsync(int intorder_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainByOrderID", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainByOrderIDResponse")]
        System.Data.DataSet UserControl_Loaded_SelectTrainByOrderID(int intorder_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainByOrderID", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainByOrderIDResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainByOrderIDAsync(int intorder_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainByOrderUsingNo", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainByOrderUsingNoRespon" +
            "se")]
        System.Data.DataSet UserControl_Loaded_SelectTrainByOrderUsingNo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainByOrderUsingNo", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_SelectTrainByOrderUsingNoRespon" +
            "se")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainByOrderUsingNoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_InsertOrder", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_InsertOrderResponse")]
        System.Data.DataSet UserControl_Loaded_InsertOrder(int intline_id, string strorder_number, string strhours, string strdistance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_InsertOrder", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_InsertOrderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_InsertOrderAsync(int intline_id, string strorder_number, string strhours, string strdistance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_InsertOrderDetail", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_InsertOrderDetailResponse")]
        System.Data.DataSet UserControl_Loaded_InsertOrderDetail(int order_id, int as_train_type, int station_id, string station_order, string day, string arrival_time, string driving_time, string using_time, string mileage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_InsertOrderDetail", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_InsertOrderDetailResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_InsertOrderDetailAsync(int order_id, int as_train_type, int station_id, string station_order, string day, string arrival_time, string driving_time, string using_time, string mileage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_UpdateTrainOrderID", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_UpdateTrainOrderIDResponse")]
        int UserControl_Loaded_UpdateTrainOrderID(int inttrain_id, int order_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_UpdateTrainOrderID", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_UpdateTrainOrderIDResponse")]
        System.Threading.Tasks.Task<int> UserControl_Loaded_UpdateTrainOrderIDAsync(int inttrain_id, int order_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_UpdateOrder", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_UpdateOrderResponse")]
        System.Data.DataSet UserControl_Loaded_UpdateOrder(int intline_id, string strorder_number, string strhours, string strdistance, int intorder_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_UpdateOrder", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_UpdateOrderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_UpdateOrderAsync(int intline_id, string strorder_number, string strhours, string strdistance, int intorder_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DeleteOrder", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DeleteOrderResponse")]
        int UserControl_Loaded_DeleteOrder(int intorder_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DeleteOrder", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DeleteOrderResponse")]
        System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteOrderAsync(int intorder_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DeleteOrderDetail", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DeleteOrderDetailResponse")]
        int UserControl_Loaded_DeleteOrderDetail(int intorder_detail_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DeleteOrderDetail", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DeleteOrderDetailResponse")]
        System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteOrderDetailAsync(int intorder_detail_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DUpdateTrainOrderID", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DUpdateTrainOrderIDResponse")]
        int UserControl_Loaded_DUpdateTrainOrderID(int inttrain_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DUpdateTrainOrderID", ReplyAction="http://tempuri.org/UC_CarOrder/UserControl_Loaded_DUpdateTrainOrderIDResponse")]
        System.Threading.Tasks.Task<int> UserControl_Loaded_DUpdateTrainOrderIDAsync(int inttrain_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UC_CarOrderChannel : TTS_2019.BLL.UC_CarOrder.UC_CarOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UC_CarOrderClient : System.ServiceModel.ClientBase<TTS_2019.BLL.UC_CarOrder.UC_CarOrder>, TTS_2019.BLL.UC_CarOrder.UC_CarOrder {
        
        public UC_CarOrderClient() {
        }
        
        public UC_CarOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UC_CarOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_CarOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_CarOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectTrainType() {
            return base.Channel.UserControl_Loaded_SelectTrainType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainTypeAsync() {
            return base.Channel.UserControl_Loaded_SelectTrainTypeAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectOrder() {
            return base.Channel.UserControl_Loaded_SelectOrder();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectOrderAsync() {
            return base.Channel.UserControl_Loaded_SelectOrderAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectOrderDetail(int intorder_id) {
            return base.Channel.UserControl_Loaded_SelectOrderDetail(intorder_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectOrderDetailAsync(int intorder_id) {
            return base.Channel.UserControl_Loaded_SelectOrderDetailAsync(intorder_id);
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectTrainByOrderID(int intorder_id) {
            return base.Channel.UserControl_Loaded_SelectTrainByOrderID(intorder_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainByOrderIDAsync(int intorder_id) {
            return base.Channel.UserControl_Loaded_SelectTrainByOrderIDAsync(intorder_id);
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectTrainByOrderUsingNo() {
            return base.Channel.UserControl_Loaded_SelectTrainByOrderUsingNo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainByOrderUsingNoAsync() {
            return base.Channel.UserControl_Loaded_SelectTrainByOrderUsingNoAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_InsertOrder(int intline_id, string strorder_number, string strhours, string strdistance) {
            return base.Channel.UserControl_Loaded_InsertOrder(intline_id, strorder_number, strhours, strdistance);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_InsertOrderAsync(int intline_id, string strorder_number, string strhours, string strdistance) {
            return base.Channel.UserControl_Loaded_InsertOrderAsync(intline_id, strorder_number, strhours, strdistance);
        }
        
        public System.Data.DataSet UserControl_Loaded_InsertOrderDetail(int order_id, int as_train_type, int station_id, string station_order, string day, string arrival_time, string driving_time, string using_time, string mileage) {
            return base.Channel.UserControl_Loaded_InsertOrderDetail(order_id, as_train_type, station_id, station_order, day, arrival_time, driving_time, using_time, mileage);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_InsertOrderDetailAsync(int order_id, int as_train_type, int station_id, string station_order, string day, string arrival_time, string driving_time, string using_time, string mileage) {
            return base.Channel.UserControl_Loaded_InsertOrderDetailAsync(order_id, as_train_type, station_id, station_order, day, arrival_time, driving_time, using_time, mileage);
        }
        
        public int UserControl_Loaded_UpdateTrainOrderID(int inttrain_id, int order_id) {
            return base.Channel.UserControl_Loaded_UpdateTrainOrderID(inttrain_id, order_id);
        }
        
        public System.Threading.Tasks.Task<int> UserControl_Loaded_UpdateTrainOrderIDAsync(int inttrain_id, int order_id) {
            return base.Channel.UserControl_Loaded_UpdateTrainOrderIDAsync(inttrain_id, order_id);
        }
        
        public System.Data.DataSet UserControl_Loaded_UpdateOrder(int intline_id, string strorder_number, string strhours, string strdistance, int intorder_id) {
            return base.Channel.UserControl_Loaded_UpdateOrder(intline_id, strorder_number, strhours, strdistance, intorder_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_UpdateOrderAsync(int intline_id, string strorder_number, string strhours, string strdistance, int intorder_id) {
            return base.Channel.UserControl_Loaded_UpdateOrderAsync(intline_id, strorder_number, strhours, strdistance, intorder_id);
        }
        
        public int UserControl_Loaded_DeleteOrder(int intorder_id) {
            return base.Channel.UserControl_Loaded_DeleteOrder(intorder_id);
        }
        
        public System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteOrderAsync(int intorder_id) {
            return base.Channel.UserControl_Loaded_DeleteOrderAsync(intorder_id);
        }
        
        public int UserControl_Loaded_DeleteOrderDetail(int intorder_detail_id) {
            return base.Channel.UserControl_Loaded_DeleteOrderDetail(intorder_detail_id);
        }
        
        public System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteOrderDetailAsync(int intorder_detail_id) {
            return base.Channel.UserControl_Loaded_DeleteOrderDetailAsync(intorder_detail_id);
        }
        
        public int UserControl_Loaded_DUpdateTrainOrderID(int inttrain_id) {
            return base.Channel.UserControl_Loaded_DUpdateTrainOrderID(inttrain_id);
        }
        
        public System.Threading.Tasks.Task<int> UserControl_Loaded_DUpdateTrainOrderIDAsync(int inttrain_id) {
            return base.Channel.UserControl_Loaded_DUpdateTrainOrderIDAsync(inttrain_id);
        }
    }
}
