//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTS_2019.BLL.UC_UpdatePassword {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.UC_UpdatePassword.UC_UpdatePassword")]
    public interface UC_UpdatePassword {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_SelectUser", ReplyAction="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_SelectUserResponse")]
        System.Data.DataSet UpdatePassword_Loaded_SelectUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_SelectUser", ReplyAction="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_SelectUserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UpdatePassword_Loaded_SelectUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_Selectpassword", ReplyAction="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_SelectpasswordResponse" +
            "")]
        System.Data.DataSet UpdatePassword_Loaded_Selectpassword(int intoperator_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_Selectpassword", ReplyAction="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_SelectpasswordResponse" +
            "")]
        System.Threading.Tasks.Task<System.Data.DataSet> UpdatePassword_Loaded_SelectpasswordAsync(int intoperator_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_UpdatePassword", ReplyAction="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_UpdatePasswordResponse" +
            "")]
        int UpdatePassword_Loaded_UpdatePassword(string stroperator_password, int intoperator_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_UpdatePassword", ReplyAction="http://tempuri.org/UC_UpdatePassword/UpdatePassword_Loaded_UpdatePasswordResponse" +
            "")]
        System.Threading.Tasks.Task<int> UpdatePassword_Loaded_UpdatePasswordAsync(string stroperator_password, int intoperator_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UC_UpdatePasswordChannel : TTS_2019.BLL.UC_UpdatePassword.UC_UpdatePassword, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UC_UpdatePasswordClient : System.ServiceModel.ClientBase<TTS_2019.BLL.UC_UpdatePassword.UC_UpdatePassword>, TTS_2019.BLL.UC_UpdatePassword.UC_UpdatePassword {
        
        public UC_UpdatePasswordClient() {
        }
        
        public UC_UpdatePasswordClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UC_UpdatePasswordClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_UpdatePasswordClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_UpdatePasswordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet UpdatePassword_Loaded_SelectUser() {
            return base.Channel.UpdatePassword_Loaded_SelectUser();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UpdatePassword_Loaded_SelectUserAsync() {
            return base.Channel.UpdatePassword_Loaded_SelectUserAsync();
        }
        
        public System.Data.DataSet UpdatePassword_Loaded_Selectpassword(int intoperator_id) {
            return base.Channel.UpdatePassword_Loaded_Selectpassword(intoperator_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UpdatePassword_Loaded_SelectpasswordAsync(int intoperator_id) {
            return base.Channel.UpdatePassword_Loaded_SelectpasswordAsync(intoperator_id);
        }
        
        public int UpdatePassword_Loaded_UpdatePassword(string stroperator_password, int intoperator_id) {
            return base.Channel.UpdatePassword_Loaded_UpdatePassword(stroperator_password, intoperator_id);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePassword_Loaded_UpdatePasswordAsync(string stroperator_password, int intoperator_id) {
            return base.Channel.UpdatePassword_Loaded_UpdatePasswordAsync(stroperator_password, intoperator_id);
        }
    }
}
