//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTS_2019.BLL.UC_MenuManagement {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.UC_MenuManagement.UC_MenuManagement")]
    public interface UC_MenuManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_SelectModular", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_SelectModularResponse")]
        System.Data.DataSet frmMenuManagement_SelectModular();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_SelectModular", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_SelectModularResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> frmMenuManagement_SelectModularAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/UserControl_Loaded_SelectPhoro", ReplyAction="http://tempuri.org/UC_MenuManagement/UserControl_Loaded_SelectPhoroResponse")]
        string UserControl_Loaded_SelectPhoro(string strLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/UserControl_Loaded_SelectPhoro", ReplyAction="http://tempuri.org/UC_MenuManagement/UserControl_Loaded_SelectPhoroResponse")]
        System.Threading.Tasks.Task<string> UserControl_Loaded_SelectPhoroAsync(string strLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_SelectLastMenu", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_SelectLastMenuResponse")]
        System.Data.DataSet frmMenuManagement_SelectLastMenu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_SelectLastMenu", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_SelectLastMenuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> frmMenuManagement_SelectLastMenuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_InsertMenu", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_InsertMenuResponse")]
        int frmMenuManagement_InsertMenu(string strmodular_name, string strmodular_code, byte[][] strmodular_icon, int intf_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_InsertMenu", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_InsertMenuResponse")]
        System.Threading.Tasks.Task<int> frmMenuManagement_InsertMenuAsync(string strmodular_name, string strmodular_code, byte[][] strmodular_icon, int intf_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_UpdatetMenu", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_UpdatetMenuResponse")]
        int frmMenuManagement_UpdatetMenu(string strmodular_name, string strmodular_code, byte[][] strmodular_icon, int intf_id, int intmodular_id, string strOldLuJing, string strTxtLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_UpdatetMenu", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_UpdatetMenuResponse")]
        System.Threading.Tasks.Task<int> frmMenuManagement_UpdatetMenuAsync(string strmodular_name, string strmodular_code, byte[][] strmodular_icon, int intf_id, int intmodular_id, string strOldLuJing, string strTxtLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_DeleteMenu", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_DeleteMenuResponse")]
        int frmMenuManagement_DeleteMenu(int intmodular_id, string strFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_MenuManagement/frmMenuManagement_DeleteMenu", ReplyAction="http://tempuri.org/UC_MenuManagement/frmMenuManagement_DeleteMenuResponse")]
        System.Threading.Tasks.Task<int> frmMenuManagement_DeleteMenuAsync(int intmodular_id, string strFileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UC_MenuManagementChannel : TTS_2019.BLL.UC_MenuManagement.UC_MenuManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UC_MenuManagementClient : System.ServiceModel.ClientBase<TTS_2019.BLL.UC_MenuManagement.UC_MenuManagement>, TTS_2019.BLL.UC_MenuManagement.UC_MenuManagement {
        
        public UC_MenuManagementClient() {
        }
        
        public UC_MenuManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UC_MenuManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_MenuManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_MenuManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet frmMenuManagement_SelectModular() {
            return base.Channel.frmMenuManagement_SelectModular();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> frmMenuManagement_SelectModularAsync() {
            return base.Channel.frmMenuManagement_SelectModularAsync();
        }
        
        public string UserControl_Loaded_SelectPhoro(string strLuJing) {
            return base.Channel.UserControl_Loaded_SelectPhoro(strLuJing);
        }
        
        public System.Threading.Tasks.Task<string> UserControl_Loaded_SelectPhoroAsync(string strLuJing) {
            return base.Channel.UserControl_Loaded_SelectPhoroAsync(strLuJing);
        }
        
        public System.Data.DataSet frmMenuManagement_SelectLastMenu() {
            return base.Channel.frmMenuManagement_SelectLastMenu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> frmMenuManagement_SelectLastMenuAsync() {
            return base.Channel.frmMenuManagement_SelectLastMenuAsync();
        }
        
        public int frmMenuManagement_InsertMenu(string strmodular_name, string strmodular_code, byte[][] strmodular_icon, int intf_id) {
            return base.Channel.frmMenuManagement_InsertMenu(strmodular_name, strmodular_code, strmodular_icon, intf_id);
        }
        
        public System.Threading.Tasks.Task<int> frmMenuManagement_InsertMenuAsync(string strmodular_name, string strmodular_code, byte[][] strmodular_icon, int intf_id) {
            return base.Channel.frmMenuManagement_InsertMenuAsync(strmodular_name, strmodular_code, strmodular_icon, intf_id);
        }
        
        public int frmMenuManagement_UpdatetMenu(string strmodular_name, string strmodular_code, byte[][] strmodular_icon, int intf_id, int intmodular_id, string strOldLuJing, string strTxtLuJing) {
            return base.Channel.frmMenuManagement_UpdatetMenu(strmodular_name, strmodular_code, strmodular_icon, intf_id, intmodular_id, strOldLuJing, strTxtLuJing);
        }
        
        public System.Threading.Tasks.Task<int> frmMenuManagement_UpdatetMenuAsync(string strmodular_name, string strmodular_code, byte[][] strmodular_icon, int intf_id, int intmodular_id, string strOldLuJing, string strTxtLuJing) {
            return base.Channel.frmMenuManagement_UpdatetMenuAsync(strmodular_name, strmodular_code, strmodular_icon, intf_id, intmodular_id, strOldLuJing, strTxtLuJing);
        }
        
        public int frmMenuManagement_DeleteMenu(int intmodular_id, string strFileName) {
            return base.Channel.frmMenuManagement_DeleteMenu(intmodular_id, strFileName);
        }
        
        public System.Threading.Tasks.Task<int> frmMenuManagement_DeleteMenuAsync(int intmodular_id, string strFileName) {
            return base.Channel.frmMenuManagement_DeleteMenuAsync(intmodular_id, strFileName);
        }
    }
}
