//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTS_2019.BLL.UC_StaffInformation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.UC_StaffInformation.UC_StaffInformation")]
    public interface UC_StaffInformation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectStaff", ReplyAction="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectStaffResponse")]
        System.Data.DataSet UserControl_Loaded_SelectStaff();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectStaff", ReplyAction="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectStaffResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectStaffAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/PicturePath", ReplyAction="http://tempuri.org/UC_StaffInformation/PicturePathResponse")]
        string PicturePath();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/PicturePath", ReplyAction="http://tempuri.org/UC_StaffInformation/PicturePathResponse")]
        System.Threading.Tasks.Task<string> PicturePathAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectPhoro", ReplyAction="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectPhoroResponse")]
        string UserControl_Loaded_SelectPhoro(string strLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectPhoro", ReplyAction="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectPhoroResponse")]
        System.Threading.Tasks.Task<string> UserControl_Loaded_SelectPhoroAsync(string strLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectGender" +
            "", ReplyAction="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectGender" +
            "Response")]
        System.Data.DataSet InsertStaffInformation_Loaded_SelectGender();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectGender" +
            "", ReplyAction="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectGender" +
            "Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> InsertStaffInformation_Loaded_SelectGenderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectWorkSt" +
            "atus", ReplyAction="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectWorkSt" +
            "atusResponse")]
        System.Data.DataSet InsertStaffInformation_Loaded_SelectWorkStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectWorkSt" +
            "atus", ReplyAction="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectWorkSt" +
            "atusResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> InsertStaffInformation_Loaded_SelectWorkStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectEmployeeType", ReplyAction="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectEmployeeTypeRespo" +
            "nse")]
        System.Data.DataSet UserControl_Loaded_SelectEmployeeType(int intfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectEmployeeType", ReplyAction="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectEmployeeTypeRespo" +
            "nse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectEmployeeTypeAsync(int intfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectPost", ReplyAction="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectPostRe" +
            "sponse")]
        System.Data.DataSet InsertStaffInformation_Loaded_SelectPost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectPost", ReplyAction="http://tempuri.org/UC_StaffInformation/InsertStaffInformation_Loaded_SelectPostRe" +
            "sponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> InsertStaffInformation_Loaded_SelectPostAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/btn_Affirm_Click_InsertStaff", ReplyAction="http://tempuri.org/UC_StaffInformation/btn_Affirm_Click_InsertStaffResponse")]
        int btn_Affirm_Click_InsertStaff(
                    int intas_employee_type_id, 
                    int intas_work_status_id, 
                    int intas_branch_id, 
                    string strstaff_name, 
                    string strstaff_number, 
                    int intas_gender_id, 
                    string strage, 
                    string strid_card, 
                    System.DateTime dtmbirth, 
                    string strphone_number, 
                    string straddress, 
                    string stre_mail, 
                    System.DateTime dtmentry_date, 
                    System.DateTime dtmdeparture_date, 
                    bool bloperator_no, 
                    byte[][] bytepicture, 
                    string strnote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/btn_Affirm_Click_InsertStaff", ReplyAction="http://tempuri.org/UC_StaffInformation/btn_Affirm_Click_InsertStaffResponse")]
        System.Threading.Tasks.Task<int> btn_Affirm_Click_InsertStaffAsync(
                    int intas_employee_type_id, 
                    int intas_work_status_id, 
                    int intas_branch_id, 
                    string strstaff_name, 
                    string strstaff_number, 
                    int intas_gender_id, 
                    string strage, 
                    string strid_card, 
                    System.DateTime dtmbirth, 
                    string strphone_number, 
                    string straddress, 
                    string stre_mail, 
                    System.DateTime dtmentry_date, 
                    System.DateTime dtmdeparture_date, 
                    bool bloperator_no, 
                    byte[][] bytepicture, 
                    string strnote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/btn_Affirm_Click_UpdateStaff", ReplyAction="http://tempuri.org/UC_StaffInformation/btn_Affirm_Click_UpdateStaffResponse")]
        int btn_Affirm_Click_UpdateStaff(
                    int intas_employee_type_id, 
                    int intas_work_status_id, 
                    int intas_branch_id, 
                    string strstaff_name, 
                    string strstaff_number, 
                    int intas_gender_id, 
                    string strage, 
                    string strid_card, 
                    System.DateTime dtmbirth, 
                    string strphone_number, 
                    string straddress, 
                    string stre_mail, 
                    System.DateTime dtmentry_date, 
                    System.DateTime dtmdeparture_date, 
                    bool bloperator_no, 
                    byte[][] bytepicture, 
                    string strnote, 
                    int intstaff_id, 
                    string strOldLuJing, 
                    string strTxtLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/btn_Affirm_Click_UpdateStaff", ReplyAction="http://tempuri.org/UC_StaffInformation/btn_Affirm_Click_UpdateStaffResponse")]
        System.Threading.Tasks.Task<int> btn_Affirm_Click_UpdateStaffAsync(
                    int intas_employee_type_id, 
                    int intas_work_status_id, 
                    int intas_branch_id, 
                    string strstaff_name, 
                    string strstaff_number, 
                    int intas_gender_id, 
                    string strage, 
                    string strid_card, 
                    System.DateTime dtmbirth, 
                    string strphone_number, 
                    string straddress, 
                    string stre_mail, 
                    System.DateTime dtmentry_date, 
                    System.DateTime dtmdeparture_date, 
                    bool bloperator_no, 
                    byte[][] bytepicture, 
                    string strnote, 
                    int intstaff_id, 
                    string strOldLuJing, 
                    string strTxtLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/btn_Delete_Click_DelectStaff", ReplyAction="http://tempuri.org/UC_StaffInformation/btn_Delete_Click_DelectStaffResponse")]
        int btn_Delete_Click_DelectStaff(int intstaff_id, string strFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/btn_Delete_Click_DelectStaff", ReplyAction="http://tempuri.org/UC_StaffInformation/btn_Delete_Click_DelectStaffResponse")]
        System.Threading.Tasks.Task<int> btn_Delete_Click_DelectStaffAsync(int intstaff_id, string strFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectWorkZheng", ReplyAction="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectWorkZhengResponse" +
            "")]
        System.Data.DataSet UserControl_Loaded_SelectWorkZheng(int intStaffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectWorkZheng", ReplyAction="http://tempuri.org/UC_StaffInformation/UserControl_Loaded_SelectWorkZhengResponse" +
            "")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectWorkZhengAsync(int intStaffID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UC_StaffInformationChannel : TTS_2019.BLL.UC_StaffInformation.UC_StaffInformation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UC_StaffInformationClient : System.ServiceModel.ClientBase<TTS_2019.BLL.UC_StaffInformation.UC_StaffInformation>, TTS_2019.BLL.UC_StaffInformation.UC_StaffInformation {
        
        public UC_StaffInformationClient() {
        }
        
        public UC_StaffInformationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UC_StaffInformationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_StaffInformationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_StaffInformationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectStaff() {
            return base.Channel.UserControl_Loaded_SelectStaff();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectStaffAsync() {
            return base.Channel.UserControl_Loaded_SelectStaffAsync();
        }
        
        public string PicturePath() {
            return base.Channel.PicturePath();
        }
        
        public System.Threading.Tasks.Task<string> PicturePathAsync() {
            return base.Channel.PicturePathAsync();
        }
        
        public string UserControl_Loaded_SelectPhoro(string strLuJing) {
            return base.Channel.UserControl_Loaded_SelectPhoro(strLuJing);
        }
        
        public System.Threading.Tasks.Task<string> UserControl_Loaded_SelectPhoroAsync(string strLuJing) {
            return base.Channel.UserControl_Loaded_SelectPhoroAsync(strLuJing);
        }
        
        public System.Data.DataSet InsertStaffInformation_Loaded_SelectGender() {
            return base.Channel.InsertStaffInformation_Loaded_SelectGender();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InsertStaffInformation_Loaded_SelectGenderAsync() {
            return base.Channel.InsertStaffInformation_Loaded_SelectGenderAsync();
        }
        
        public System.Data.DataSet InsertStaffInformation_Loaded_SelectWorkStatus() {
            return base.Channel.InsertStaffInformation_Loaded_SelectWorkStatus();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InsertStaffInformation_Loaded_SelectWorkStatusAsync() {
            return base.Channel.InsertStaffInformation_Loaded_SelectWorkStatusAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectEmployeeType(int intfid) {
            return base.Channel.UserControl_Loaded_SelectEmployeeType(intfid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectEmployeeTypeAsync(int intfid) {
            return base.Channel.UserControl_Loaded_SelectEmployeeTypeAsync(intfid);
        }
        
        public System.Data.DataSet InsertStaffInformation_Loaded_SelectPost() {
            return base.Channel.InsertStaffInformation_Loaded_SelectPost();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InsertStaffInformation_Loaded_SelectPostAsync() {
            return base.Channel.InsertStaffInformation_Loaded_SelectPostAsync();
        }
        
        public int btn_Affirm_Click_InsertStaff(
                    int intas_employee_type_id, 
                    int intas_work_status_id, 
                    int intas_branch_id, 
                    string strstaff_name, 
                    string strstaff_number, 
                    int intas_gender_id, 
                    string strage, 
                    string strid_card, 
                    System.DateTime dtmbirth, 
                    string strphone_number, 
                    string straddress, 
                    string stre_mail, 
                    System.DateTime dtmentry_date, 
                    System.DateTime dtmdeparture_date, 
                    bool bloperator_no, 
                    byte[][] bytepicture, 
                    string strnote) {
            return base.Channel.btn_Affirm_Click_InsertStaff(intas_employee_type_id, intas_work_status_id, intas_branch_id, strstaff_name, strstaff_number, intas_gender_id, strage, strid_card, dtmbirth, strphone_number, straddress, stre_mail, dtmentry_date, dtmdeparture_date, bloperator_no, bytepicture, strnote);
        }
        
        public System.Threading.Tasks.Task<int> btn_Affirm_Click_InsertStaffAsync(
                    int intas_employee_type_id, 
                    int intas_work_status_id, 
                    int intas_branch_id, 
                    string strstaff_name, 
                    string strstaff_number, 
                    int intas_gender_id, 
                    string strage, 
                    string strid_card, 
                    System.DateTime dtmbirth, 
                    string strphone_number, 
                    string straddress, 
                    string stre_mail, 
                    System.DateTime dtmentry_date, 
                    System.DateTime dtmdeparture_date, 
                    bool bloperator_no, 
                    byte[][] bytepicture, 
                    string strnote) {
            return base.Channel.btn_Affirm_Click_InsertStaffAsync(intas_employee_type_id, intas_work_status_id, intas_branch_id, strstaff_name, strstaff_number, intas_gender_id, strage, strid_card, dtmbirth, strphone_number, straddress, stre_mail, dtmentry_date, dtmdeparture_date, bloperator_no, bytepicture, strnote);
        }
        
        public int btn_Affirm_Click_UpdateStaff(
                    int intas_employee_type_id, 
                    int intas_work_status_id, 
                    int intas_branch_id, 
                    string strstaff_name, 
                    string strstaff_number, 
                    int intas_gender_id, 
                    string strage, 
                    string strid_card, 
                    System.DateTime dtmbirth, 
                    string strphone_number, 
                    string straddress, 
                    string stre_mail, 
                    System.DateTime dtmentry_date, 
                    System.DateTime dtmdeparture_date, 
                    bool bloperator_no, 
                    byte[][] bytepicture, 
                    string strnote, 
                    int intstaff_id, 
                    string strOldLuJing, 
                    string strTxtLuJing) {
            return base.Channel.btn_Affirm_Click_UpdateStaff(intas_employee_type_id, intas_work_status_id, intas_branch_id, strstaff_name, strstaff_number, intas_gender_id, strage, strid_card, dtmbirth, strphone_number, straddress, stre_mail, dtmentry_date, dtmdeparture_date, bloperator_no, bytepicture, strnote, intstaff_id, strOldLuJing, strTxtLuJing);
        }
        
        public System.Threading.Tasks.Task<int> btn_Affirm_Click_UpdateStaffAsync(
                    int intas_employee_type_id, 
                    int intas_work_status_id, 
                    int intas_branch_id, 
                    string strstaff_name, 
                    string strstaff_number, 
                    int intas_gender_id, 
                    string strage, 
                    string strid_card, 
                    System.DateTime dtmbirth, 
                    string strphone_number, 
                    string straddress, 
                    string stre_mail, 
                    System.DateTime dtmentry_date, 
                    System.DateTime dtmdeparture_date, 
                    bool bloperator_no, 
                    byte[][] bytepicture, 
                    string strnote, 
                    int intstaff_id, 
                    string strOldLuJing, 
                    string strTxtLuJing) {
            return base.Channel.btn_Affirm_Click_UpdateStaffAsync(intas_employee_type_id, intas_work_status_id, intas_branch_id, strstaff_name, strstaff_number, intas_gender_id, strage, strid_card, dtmbirth, strphone_number, straddress, stre_mail, dtmentry_date, dtmdeparture_date, bloperator_no, bytepicture, strnote, intstaff_id, strOldLuJing, strTxtLuJing);
        }
        
        public int btn_Delete_Click_DelectStaff(int intstaff_id, string strFileName) {
            return base.Channel.btn_Delete_Click_DelectStaff(intstaff_id, strFileName);
        }
        
        public System.Threading.Tasks.Task<int> btn_Delete_Click_DelectStaffAsync(int intstaff_id, string strFileName) {
            return base.Channel.btn_Delete_Click_DelectStaffAsync(intstaff_id, strFileName);
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectWorkZheng(int intStaffID) {
            return base.Channel.UserControl_Loaded_SelectWorkZheng(intStaffID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectWorkZhengAsync(int intStaffID) {
            return base.Channel.UserControl_Loaded_SelectWorkZhengAsync(intStaffID);
        }
    }
}
