//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTS_2019.BLL.UC_StaffAccountManage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.UC_StaffAccountManage.UC_StaffAccountManage")]
    public interface UC_StaffAccountManage {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/UserControl_Loaded_SelectStaffAccountMan" +
            "age", ReplyAction="http://tempuri.org/UC_StaffAccountManage/UserControl_Loaded_SelectStaffAccountMan" +
            "ageResponse")]
        System.Data.DataSet UserControl_Loaded_SelectStaffAccountManage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/UserControl_Loaded_SelectStaffAccountMan" +
            "age", ReplyAction="http://tempuri.org/UC_StaffAccountManage/UserControl_Loaded_SelectStaffAccountMan" +
            "ageResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectStaffAccountManageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_SelectStaffManage", ReplyAction="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_SelectStaffManageResponse")]
        System.Data.DataSet Window_Loaded_SelectStaffManage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_SelectStaffManage", ReplyAction="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_SelectStaffManageResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Window_Loaded_SelectStaffManageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_SelectUserGroup", ReplyAction="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_SelectUserGroupResponse")]
        System.Data.DataSet Window_Loaded_SelectUserGroup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_SelectUserGroup", ReplyAction="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_SelectUserGroupResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Window_Loaded_SelectUserGroupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_InsertStaffAccountManag" +
            "e", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_InsertStaffAccountManag" +
            "eResponse")]
        int btn_Affirm_Click_InsertStaffAccountManage(int intID, int intgroup_id, string strAccounts, string strPassword, bool blEffective, string strNote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_InsertStaffAccountManag" +
            "e", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_InsertStaffAccountManag" +
            "eResponse")]
        System.Threading.Tasks.Task<int> btn_Affirm_Click_InsertStaffAccountManageAsync(int intID, int intgroup_id, string strAccounts, string strPassword, bool blEffective, string strNote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_USelectStaffManage", ReplyAction="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_USelectStaffManageResponse" +
            "")]
        System.Data.DataSet Window_Loaded_USelectStaffManage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_USelectStaffManage", ReplyAction="http://tempuri.org/UC_StaffAccountManage/Window_Loaded_USelectStaffManageResponse" +
            "")]
        System.Threading.Tasks.Task<System.Data.DataSet> Window_Loaded_USelectStaffManageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_UpdateStaffAccountManag" +
            "e", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_UpdateStaffAccountManag" +
            "eResponse")]
        int btn_Affirm_Click_UpdateStaffAccountManage(int intStaffID, int intGroupID, string strAccounts, string strPassword, bool blEffective, string strNote, int intOperatorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_UpdateStaffAccountManag" +
            "e", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_UpdateStaffAccountManag" +
            "eResponse")]
        System.Threading.Tasks.Task<int> btn_Affirm_Click_UpdateStaffAccountManageAsync(int intStaffID, int intGroupID, string strAccounts, string strPassword, bool blEffective, string strNote, int intOperatorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_DeleteStaffAccountManag" +
            "e", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_DeleteStaffAccountManag" +
            "eResponse")]
        int btn_Affirm_Click_DeleteStaffAccountManage(int intOperatorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_DeleteStaffAccountManag" +
            "e", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btn_Affirm_Click_DeleteStaffAccountManag" +
            "eResponse")]
        System.Threading.Tasks.Task<int> btn_Affirm_Click_DeleteStaffAccountManageAsync(int intOperatorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btnSave_Click_SeleteStaffId", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btnSave_Click_SeleteStaffIdResponse")]
        System.Data.DataSet btnSave_Click_SeleteStaffId(string strStaffName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btnSave_Click_SeleteStaffId", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btnSave_Click_SeleteStaffIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnSave_Click_SeleteStaffIdAsync(string strStaffName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btnSave_Click_SeletePGroupId", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btnSave_Click_SeletePGroupIdResponse")]
        System.Data.DataSet btnSave_Click_SeletePGroupId(string strPName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_StaffAccountManage/btnSave_Click_SeletePGroupId", ReplyAction="http://tempuri.org/UC_StaffAccountManage/btnSave_Click_SeletePGroupIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> btnSave_Click_SeletePGroupIdAsync(string strPName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UC_StaffAccountManageChannel : TTS_2019.BLL.UC_StaffAccountManage.UC_StaffAccountManage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UC_StaffAccountManageClient : System.ServiceModel.ClientBase<TTS_2019.BLL.UC_StaffAccountManage.UC_StaffAccountManage>, TTS_2019.BLL.UC_StaffAccountManage.UC_StaffAccountManage {
        
        public UC_StaffAccountManageClient() {
        }
        
        public UC_StaffAccountManageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UC_StaffAccountManageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_StaffAccountManageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_StaffAccountManageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectStaffAccountManage() {
            return base.Channel.UserControl_Loaded_SelectStaffAccountManage();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectStaffAccountManageAsync() {
            return base.Channel.UserControl_Loaded_SelectStaffAccountManageAsync();
        }
        
        public System.Data.DataSet Window_Loaded_SelectStaffManage() {
            return base.Channel.Window_Loaded_SelectStaffManage();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Window_Loaded_SelectStaffManageAsync() {
            return base.Channel.Window_Loaded_SelectStaffManageAsync();
        }
        
        public System.Data.DataSet Window_Loaded_SelectUserGroup() {
            return base.Channel.Window_Loaded_SelectUserGroup();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Window_Loaded_SelectUserGroupAsync() {
            return base.Channel.Window_Loaded_SelectUserGroupAsync();
        }
        
        public int btn_Affirm_Click_InsertStaffAccountManage(int intID, int intgroup_id, string strAccounts, string strPassword, bool blEffective, string strNote) {
            return base.Channel.btn_Affirm_Click_InsertStaffAccountManage(intID, intgroup_id, strAccounts, strPassword, blEffective, strNote);
        }
        
        public System.Threading.Tasks.Task<int> btn_Affirm_Click_InsertStaffAccountManageAsync(int intID, int intgroup_id, string strAccounts, string strPassword, bool blEffective, string strNote) {
            return base.Channel.btn_Affirm_Click_InsertStaffAccountManageAsync(intID, intgroup_id, strAccounts, strPassword, blEffective, strNote);
        }
        
        public System.Data.DataSet Window_Loaded_USelectStaffManage() {
            return base.Channel.Window_Loaded_USelectStaffManage();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Window_Loaded_USelectStaffManageAsync() {
            return base.Channel.Window_Loaded_USelectStaffManageAsync();
        }
        
        public int btn_Affirm_Click_UpdateStaffAccountManage(int intStaffID, int intGroupID, string strAccounts, string strPassword, bool blEffective, string strNote, int intOperatorID) {
            return base.Channel.btn_Affirm_Click_UpdateStaffAccountManage(intStaffID, intGroupID, strAccounts, strPassword, blEffective, strNote, intOperatorID);
        }
        
        public System.Threading.Tasks.Task<int> btn_Affirm_Click_UpdateStaffAccountManageAsync(int intStaffID, int intGroupID, string strAccounts, string strPassword, bool blEffective, string strNote, int intOperatorID) {
            return base.Channel.btn_Affirm_Click_UpdateStaffAccountManageAsync(intStaffID, intGroupID, strAccounts, strPassword, blEffective, strNote, intOperatorID);
        }
        
        public int btn_Affirm_Click_DeleteStaffAccountManage(int intOperatorID) {
            return base.Channel.btn_Affirm_Click_DeleteStaffAccountManage(intOperatorID);
        }
        
        public System.Threading.Tasks.Task<int> btn_Affirm_Click_DeleteStaffAccountManageAsync(int intOperatorID) {
            return base.Channel.btn_Affirm_Click_DeleteStaffAccountManageAsync(intOperatorID);
        }
        
        public System.Data.DataSet btnSave_Click_SeleteStaffId(string strStaffName) {
            return base.Channel.btnSave_Click_SeleteStaffId(strStaffName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnSave_Click_SeleteStaffIdAsync(string strStaffName) {
            return base.Channel.btnSave_Click_SeleteStaffIdAsync(strStaffName);
        }
        
        public System.Data.DataSet btnSave_Click_SeletePGroupId(string strPName) {
            return base.Channel.btnSave_Click_SeletePGroupId(strPName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> btnSave_Click_SeletePGroupIdAsync(string strPName) {
            return base.Channel.btnSave_Click_SeletePGroupIdAsync(strPName);
        }
    }
}
