//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTS_2019.BLL.UC_Compartment {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.UC_Compartment.UC_Compartment")]
    public interface UC_Compartment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainSum", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainSumResponse")]
        System.Data.DataSet UserControl_Loaded_SelectTrainSum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainSum", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainSumResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainSumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainType", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainTypeResponse")]
        System.Data.DataSet UserControl_Loaded_SelectTrainType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainType", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectCompartmentType", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectCompartmentTypeRespons" +
            "e")]
        System.Data.DataSet UserControl_Loaded_SelectCompartmentType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectCompartmentType", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectCompartmentTypeRespons" +
            "e")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectCompartmentTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectSeatType", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectSeatTypeResponse")]
        System.Data.DataSet UserControl_Loaded_SelectSeatType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectSeatType", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectSeatTypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectSeatTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_Selectprincipal", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectprincipalResponse")]
        System.Data.DataSet UserControl_Loaded_Selectprincipal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_Selectprincipal", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectprincipalResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectprincipalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_Selectlinkman", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectlinkmanResponse")]
        System.Data.DataSet UserControl_Loaded_Selectlinkman();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_Selectlinkman", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectlinkmanResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectlinkmanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrain", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainResponse")]
        System.Data.DataSet UserControl_Loaded_SelectTrain();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrain", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectTrainResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectCompartment", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectCompartmentResponse")]
        System.Data.DataSet UserControl_Loaded_SelectCompartment(int inttrain_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectCompartment", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectCompartmentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectCompartmentAsync(int inttrain_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectSeat", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectSeatResponse")]
        System.Data.DataSet UserControl_Loaded_SelectSeat(int intcar_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectSeat", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectSeatResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectSeatAsync(int intcar_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectPhoro", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectPhoroResponse")]
        string[] UserControl_Loaded_SelectPhoro(string strLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectPhoro", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_SelectPhoroResponse")]
        System.Threading.Tasks.Task<string[]> UserControl_Loaded_SelectPhoroAsync(string strLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertTrain", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertTrainResponse")]
        System.Data.DataSet UserControl_Loaded_InsertTrain(int intas_type_id, int intprincipal_id, int intlinkman_id, string strtrain_number, string strbottom_number, System.DateTime dtproduction_date, System.DateTime dtexpiration_date, string strbiggest_pitch, byte[][] strimage_path, bool blusing_no, bool bldisable, string strnote, string strrate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertTrain", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertTrainResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_InsertTrainAsync(int intas_type_id, int intprincipal_id, int intlinkman_id, string strtrain_number, string strbottom_number, System.DateTime dtproduction_date, System.DateTime dtexpiration_date, string strbiggest_pitch, byte[][] strimage_path, bool blusing_no, bool bldisable, string strnote, string strrate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertCar", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertCarResponse")]
        System.Data.DataSet UserControl_Loaded_InsertCar(int intas_car_type_id, string strcar_number, string strnote, int inttrain_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertCar", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertCarResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_InsertCarAsync(int intas_car_type_id, string strcar_number, string strnote, int inttrain_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertCarSeat", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertCarSeatResponse")]
        int UserControl_Loaded_InsertCarSeat(int intcar_id, int intas_seat_type_id, string strseat_number, string strnote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertCarSeat", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_InsertCarSeatResponse")]
        System.Threading.Tasks.Task<int> UserControl_Loaded_InsertCarSeatAsync(int intcar_id, int intas_seat_type_id, string strseat_number, string strnote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_UpdateTrain", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_UpdateTrainResponse")]
        System.Data.DataSet UserControl_Loaded_UpdateTrain(
                    int intas_type_id, 
                    int intprincipal_id, 
                    int intlinkman_id, 
                    string strtrain_number, 
                    string strbottom_number, 
                    System.DateTime dtproduction_date, 
                    System.DateTime dtexpiration_date, 
                    string strbiggest_pitch, 
                    byte[][] strimage_path, 
                    bool blusing_no, 
                    bool bldisable, 
                    string strnote, 
                    string strrate, 
                    int inttrain_id, 
                    string strOldLuJing, 
                    string strTxtLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_UpdateTrain", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_UpdateTrainResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_UpdateTrainAsync(
                    int intas_type_id, 
                    int intprincipal_id, 
                    int intlinkman_id, 
                    string strtrain_number, 
                    string strbottom_number, 
                    System.DateTime dtproduction_date, 
                    System.DateTime dtexpiration_date, 
                    string strbiggest_pitch, 
                    byte[][] strimage_path, 
                    bool blusing_no, 
                    bool bldisable, 
                    string strnote, 
                    string strrate, 
                    int inttrain_id, 
                    string strOldLuJing, 
                    string strTxtLuJing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteTrain", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteTrainResponse")]
        int UserControl_Loaded_DeleteTrain(int inttrain_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteTrain", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteTrainResponse")]
        System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteTrainAsync(int inttrain_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteCar", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteCarResponse")]
        int UserControl_Loaded_DeleteCar(int intcar_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteCar", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteCarResponse")]
        System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteCarAsync(int intcar_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteCarSeat", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteCarSeatResponse")]
        int UserControl_Loaded_DeleteCarSeat(int intseat_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteCarSeat", ReplyAction="http://tempuri.org/UC_Compartment/UserControl_Loaded_DeleteCarSeatResponse")]
        System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteCarSeatAsync(int intseat_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UC_CompartmentChannel : TTS_2019.BLL.UC_Compartment.UC_Compartment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UC_CompartmentClient : System.ServiceModel.ClientBase<TTS_2019.BLL.UC_Compartment.UC_Compartment>, TTS_2019.BLL.UC_Compartment.UC_Compartment {
        
        public UC_CompartmentClient() {
        }
        
        public UC_CompartmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UC_CompartmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_CompartmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_CompartmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectTrainSum() {
            return base.Channel.UserControl_Loaded_SelectTrainSum();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainSumAsync() {
            return base.Channel.UserControl_Loaded_SelectTrainSumAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectTrainType() {
            return base.Channel.UserControl_Loaded_SelectTrainType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainTypeAsync() {
            return base.Channel.UserControl_Loaded_SelectTrainTypeAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectCompartmentType() {
            return base.Channel.UserControl_Loaded_SelectCompartmentType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectCompartmentTypeAsync() {
            return base.Channel.UserControl_Loaded_SelectCompartmentTypeAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectSeatType() {
            return base.Channel.UserControl_Loaded_SelectSeatType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectSeatTypeAsync() {
            return base.Channel.UserControl_Loaded_SelectSeatTypeAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_Selectprincipal() {
            return base.Channel.UserControl_Loaded_Selectprincipal();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectprincipalAsync() {
            return base.Channel.UserControl_Loaded_SelectprincipalAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_Selectlinkman() {
            return base.Channel.UserControl_Loaded_Selectlinkman();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectlinkmanAsync() {
            return base.Channel.UserControl_Loaded_SelectlinkmanAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectTrain() {
            return base.Channel.UserControl_Loaded_SelectTrain();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTrainAsync() {
            return base.Channel.UserControl_Loaded_SelectTrainAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectCompartment(int inttrain_id) {
            return base.Channel.UserControl_Loaded_SelectCompartment(inttrain_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectCompartmentAsync(int inttrain_id) {
            return base.Channel.UserControl_Loaded_SelectCompartmentAsync(inttrain_id);
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectSeat(int intcar_id) {
            return base.Channel.UserControl_Loaded_SelectSeat(intcar_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectSeatAsync(int intcar_id) {
            return base.Channel.UserControl_Loaded_SelectSeatAsync(intcar_id);
        }
        
        public string[] UserControl_Loaded_SelectPhoro(string strLuJing) {
            return base.Channel.UserControl_Loaded_SelectPhoro(strLuJing);
        }
        
        public System.Threading.Tasks.Task<string[]> UserControl_Loaded_SelectPhoroAsync(string strLuJing) {
            return base.Channel.UserControl_Loaded_SelectPhoroAsync(strLuJing);
        }
        
        public System.Data.DataSet UserControl_Loaded_InsertTrain(int intas_type_id, int intprincipal_id, int intlinkman_id, string strtrain_number, string strbottom_number, System.DateTime dtproduction_date, System.DateTime dtexpiration_date, string strbiggest_pitch, byte[][] strimage_path, bool blusing_no, bool bldisable, string strnote, string strrate) {
            return base.Channel.UserControl_Loaded_InsertTrain(intas_type_id, intprincipal_id, intlinkman_id, strtrain_number, strbottom_number, dtproduction_date, dtexpiration_date, strbiggest_pitch, strimage_path, blusing_no, bldisable, strnote, strrate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_InsertTrainAsync(int intas_type_id, int intprincipal_id, int intlinkman_id, string strtrain_number, string strbottom_number, System.DateTime dtproduction_date, System.DateTime dtexpiration_date, string strbiggest_pitch, byte[][] strimage_path, bool blusing_no, bool bldisable, string strnote, string strrate) {
            return base.Channel.UserControl_Loaded_InsertTrainAsync(intas_type_id, intprincipal_id, intlinkman_id, strtrain_number, strbottom_number, dtproduction_date, dtexpiration_date, strbiggest_pitch, strimage_path, blusing_no, bldisable, strnote, strrate);
        }
        
        public System.Data.DataSet UserControl_Loaded_InsertCar(int intas_car_type_id, string strcar_number, string strnote, int inttrain_id) {
            return base.Channel.UserControl_Loaded_InsertCar(intas_car_type_id, strcar_number, strnote, inttrain_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_InsertCarAsync(int intas_car_type_id, string strcar_number, string strnote, int inttrain_id) {
            return base.Channel.UserControl_Loaded_InsertCarAsync(intas_car_type_id, strcar_number, strnote, inttrain_id);
        }
        
        public int UserControl_Loaded_InsertCarSeat(int intcar_id, int intas_seat_type_id, string strseat_number, string strnote) {
            return base.Channel.UserControl_Loaded_InsertCarSeat(intcar_id, intas_seat_type_id, strseat_number, strnote);
        }
        
        public System.Threading.Tasks.Task<int> UserControl_Loaded_InsertCarSeatAsync(int intcar_id, int intas_seat_type_id, string strseat_number, string strnote) {
            return base.Channel.UserControl_Loaded_InsertCarSeatAsync(intcar_id, intas_seat_type_id, strseat_number, strnote);
        }
        
        public System.Data.DataSet UserControl_Loaded_UpdateTrain(
                    int intas_type_id, 
                    int intprincipal_id, 
                    int intlinkman_id, 
                    string strtrain_number, 
                    string strbottom_number, 
                    System.DateTime dtproduction_date, 
                    System.DateTime dtexpiration_date, 
                    string strbiggest_pitch, 
                    byte[][] strimage_path, 
                    bool blusing_no, 
                    bool bldisable, 
                    string strnote, 
                    string strrate, 
                    int inttrain_id, 
                    string strOldLuJing, 
                    string strTxtLuJing) {
            return base.Channel.UserControl_Loaded_UpdateTrain(intas_type_id, intprincipal_id, intlinkman_id, strtrain_number, strbottom_number, dtproduction_date, dtexpiration_date, strbiggest_pitch, strimage_path, blusing_no, bldisable, strnote, strrate, inttrain_id, strOldLuJing, strTxtLuJing);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_UpdateTrainAsync(
                    int intas_type_id, 
                    int intprincipal_id, 
                    int intlinkman_id, 
                    string strtrain_number, 
                    string strbottom_number, 
                    System.DateTime dtproduction_date, 
                    System.DateTime dtexpiration_date, 
                    string strbiggest_pitch, 
                    byte[][] strimage_path, 
                    bool blusing_no, 
                    bool bldisable, 
                    string strnote, 
                    string strrate, 
                    int inttrain_id, 
                    string strOldLuJing, 
                    string strTxtLuJing) {
            return base.Channel.UserControl_Loaded_UpdateTrainAsync(intas_type_id, intprincipal_id, intlinkman_id, strtrain_number, strbottom_number, dtproduction_date, dtexpiration_date, strbiggest_pitch, strimage_path, blusing_no, bldisable, strnote, strrate, inttrain_id, strOldLuJing, strTxtLuJing);
        }
        
        public int UserControl_Loaded_DeleteTrain(int inttrain_id) {
            return base.Channel.UserControl_Loaded_DeleteTrain(inttrain_id);
        }
        
        public System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteTrainAsync(int inttrain_id) {
            return base.Channel.UserControl_Loaded_DeleteTrainAsync(inttrain_id);
        }
        
        public int UserControl_Loaded_DeleteCar(int intcar_id) {
            return base.Channel.UserControl_Loaded_DeleteCar(intcar_id);
        }
        
        public System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteCarAsync(int intcar_id) {
            return base.Channel.UserControl_Loaded_DeleteCarAsync(intcar_id);
        }
        
        public int UserControl_Loaded_DeleteCarSeat(int intseat_id) {
            return base.Channel.UserControl_Loaded_DeleteCarSeat(intseat_id);
        }
        
        public System.Threading.Tasks.Task<int> UserControl_Loaded_DeleteCarSeatAsync(int intseat_id) {
            return base.Channel.UserControl_Loaded_DeleteCarSeatAsync(intseat_id);
        }
    }
}
