//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTS_2019.BLL.UC_TravellerInformation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL.UC_TravellerInformation.UC_TravellerInformation")]
    public interface UC_TravellerInformation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectCertificateTy" +
            "pe", ReplyAction="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectCertificateTy" +
            "peResponse")]
        System.Data.DataSet UserControl_Loaded_SelectCertificateType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectCertificateTy" +
            "pe", ReplyAction="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectCertificateTy" +
            "peResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectCertificateTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerType" +
            "", ReplyAction="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerType" +
            "Response")]
        System.Data.DataSet UserControl_Loaded_SelectTravellerType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerType" +
            "", ReplyAction="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerType" +
            "Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTravellerTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/InsertTravellerInformation_Loaded_Sele" +
            "ctGender", ReplyAction="http://tempuri.org/UC_TravellerInformation/InsertTravellerInformation_Loaded_Sele" +
            "ctGenderResponse")]
        System.Data.DataSet InsertTravellerInformation_Loaded_SelectGender();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/InsertTravellerInformation_Loaded_Sele" +
            "ctGender", ReplyAction="http://tempuri.org/UC_TravellerInformation/InsertTravellerInformation_Loaded_Sele" +
            "ctGenderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> InsertTravellerInformation_Loaded_SelectGenderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTraveller", ReplyAction="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerResp" +
            "onse")]
        System.Data.DataSet UserControl_Loaded_SelectTraveller();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTraveller", ReplyAction="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerResp" +
            "onse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTravellerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/btn_Affirm_Click_InsertTraveller", ReplyAction="http://tempuri.org/UC_TravellerInformation/btn_Affirm_Click_InsertTravellerRespon" +
            "se")]
        int btn_Affirm_Click_InsertTraveller(int intas_certificate_type_id, int intas_passenger_type_id, int intas_gender_id, string strtraveller_name, System.DateTime date_of_birth, string strage, string strcountry_or_region, string strcertificate_number, string strphone_number, string straddress, string stremergency_phone, string stremergency_address, string strzip_code, System.DateTime register_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/btn_Affirm_Click_InsertTraveller", ReplyAction="http://tempuri.org/UC_TravellerInformation/btn_Affirm_Click_InsertTravellerRespon" +
            "se")]
        System.Threading.Tasks.Task<int> btn_Affirm_Click_InsertTravellerAsync(int intas_certificate_type_id, int intas_passenger_type_id, int intas_gender_id, string strtraveller_name, System.DateTime date_of_birth, string strage, string strcountry_or_region, string strcertificate_number, string strphone_number, string straddress, string stremergency_phone, string stremergency_address, string strzip_code, System.DateTime register_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/btn_Affirm_Click_UpdateTraveller", ReplyAction="http://tempuri.org/UC_TravellerInformation/btn_Affirm_Click_UpdateTravellerRespon" +
            "se")]
        int btn_Affirm_Click_UpdateTraveller(int intas_certificate_type_id, int intas_passenger_type_id, int intas_gender_id, string strtraveller_name, System.DateTime date_of_birth, string strage, string strcountry_or_region, string strcertificate_number, string strphone_number, string straddress, string stremergency_phone, string stremergency_address, string strzip_code, System.DateTime register_date, int inttraveller_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/btn_Affirm_Click_UpdateTraveller", ReplyAction="http://tempuri.org/UC_TravellerInformation/btn_Affirm_Click_UpdateTravellerRespon" +
            "se")]
        System.Threading.Tasks.Task<int> btn_Affirm_Click_UpdateTravellerAsync(int intas_certificate_type_id, int intas_passenger_type_id, int intas_gender_id, string strtraveller_name, System.DateTime date_of_birth, string strage, string strcountry_or_region, string strcertificate_number, string strphone_number, string straddress, string stremergency_phone, string stremergency_address, string strzip_code, System.DateTime register_date, int inttraveller_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/btn_Delete_Click_DelectTraveller", ReplyAction="http://tempuri.org/UC_TravellerInformation/btn_Delete_Click_DelectTravellerRespon" +
            "se")]
        int btn_Delete_Click_DelectTraveller(int inttraveller_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/btn_Delete_Click_DelectTraveller", ReplyAction="http://tempuri.org/UC_TravellerInformation/btn_Delete_Click_DelectTravellerRespon" +
            "se")]
        System.Threading.Tasks.Task<int> btn_Delete_Click_DelectTravellerAsync(int inttraveller_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerCoun" +
            "trySum", ReplyAction="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerCoun" +
            "trySumResponse")]
        System.Data.DataSet UserControl_Loaded_SelectTravellerCountrySum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerCoun" +
            "trySum", ReplyAction="http://tempuri.org/UC_TravellerInformation/UserControl_Loaded_SelectTravellerCoun" +
            "trySumResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTravellerCountrySumAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UC_TravellerInformationChannel : TTS_2019.BLL.UC_TravellerInformation.UC_TravellerInformation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UC_TravellerInformationClient : System.ServiceModel.ClientBase<TTS_2019.BLL.UC_TravellerInformation.UC_TravellerInformation>, TTS_2019.BLL.UC_TravellerInformation.UC_TravellerInformation {
        
        public UC_TravellerInformationClient() {
        }
        
        public UC_TravellerInformationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UC_TravellerInformationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_TravellerInformationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UC_TravellerInformationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectCertificateType() {
            return base.Channel.UserControl_Loaded_SelectCertificateType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectCertificateTypeAsync() {
            return base.Channel.UserControl_Loaded_SelectCertificateTypeAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectTravellerType() {
            return base.Channel.UserControl_Loaded_SelectTravellerType();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTravellerTypeAsync() {
            return base.Channel.UserControl_Loaded_SelectTravellerTypeAsync();
        }
        
        public System.Data.DataSet InsertTravellerInformation_Loaded_SelectGender() {
            return base.Channel.InsertTravellerInformation_Loaded_SelectGender();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InsertTravellerInformation_Loaded_SelectGenderAsync() {
            return base.Channel.InsertTravellerInformation_Loaded_SelectGenderAsync();
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectTraveller() {
            return base.Channel.UserControl_Loaded_SelectTraveller();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTravellerAsync() {
            return base.Channel.UserControl_Loaded_SelectTravellerAsync();
        }
        
        public int btn_Affirm_Click_InsertTraveller(int intas_certificate_type_id, int intas_passenger_type_id, int intas_gender_id, string strtraveller_name, System.DateTime date_of_birth, string strage, string strcountry_or_region, string strcertificate_number, string strphone_number, string straddress, string stremergency_phone, string stremergency_address, string strzip_code, System.DateTime register_date) {
            return base.Channel.btn_Affirm_Click_InsertTraveller(intas_certificate_type_id, intas_passenger_type_id, intas_gender_id, strtraveller_name, date_of_birth, strage, strcountry_or_region, strcertificate_number, strphone_number, straddress, stremergency_phone, stremergency_address, strzip_code, register_date);
        }
        
        public System.Threading.Tasks.Task<int> btn_Affirm_Click_InsertTravellerAsync(int intas_certificate_type_id, int intas_passenger_type_id, int intas_gender_id, string strtraveller_name, System.DateTime date_of_birth, string strage, string strcountry_or_region, string strcertificate_number, string strphone_number, string straddress, string stremergency_phone, string stremergency_address, string strzip_code, System.DateTime register_date) {
            return base.Channel.btn_Affirm_Click_InsertTravellerAsync(intas_certificate_type_id, intas_passenger_type_id, intas_gender_id, strtraveller_name, date_of_birth, strage, strcountry_or_region, strcertificate_number, strphone_number, straddress, stremergency_phone, stremergency_address, strzip_code, register_date);
        }
        
        public int btn_Affirm_Click_UpdateTraveller(int intas_certificate_type_id, int intas_passenger_type_id, int intas_gender_id, string strtraveller_name, System.DateTime date_of_birth, string strage, string strcountry_or_region, string strcertificate_number, string strphone_number, string straddress, string stremergency_phone, string stremergency_address, string strzip_code, System.DateTime register_date, int inttraveller_id) {
            return base.Channel.btn_Affirm_Click_UpdateTraveller(intas_certificate_type_id, intas_passenger_type_id, intas_gender_id, strtraveller_name, date_of_birth, strage, strcountry_or_region, strcertificate_number, strphone_number, straddress, stremergency_phone, stremergency_address, strzip_code, register_date, inttraveller_id);
        }
        
        public System.Threading.Tasks.Task<int> btn_Affirm_Click_UpdateTravellerAsync(int intas_certificate_type_id, int intas_passenger_type_id, int intas_gender_id, string strtraveller_name, System.DateTime date_of_birth, string strage, string strcountry_or_region, string strcertificate_number, string strphone_number, string straddress, string stremergency_phone, string stremergency_address, string strzip_code, System.DateTime register_date, int inttraveller_id) {
            return base.Channel.btn_Affirm_Click_UpdateTravellerAsync(intas_certificate_type_id, intas_passenger_type_id, intas_gender_id, strtraveller_name, date_of_birth, strage, strcountry_or_region, strcertificate_number, strphone_number, straddress, stremergency_phone, stremergency_address, strzip_code, register_date, inttraveller_id);
        }
        
        public int btn_Delete_Click_DelectTraveller(int inttraveller_id) {
            return base.Channel.btn_Delete_Click_DelectTraveller(inttraveller_id);
        }
        
        public System.Threading.Tasks.Task<int> btn_Delete_Click_DelectTravellerAsync(int inttraveller_id) {
            return base.Channel.btn_Delete_Click_DelectTravellerAsync(inttraveller_id);
        }
        
        public System.Data.DataSet UserControl_Loaded_SelectTravellerCountrySum() {
            return base.Channel.UserControl_Loaded_SelectTravellerCountrySum();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UserControl_Loaded_SelectTravellerCountrySumAsync() {
            return base.Channel.UserControl_Loaded_SelectTravellerCountrySumAsync();
        }
    }
}
